name: "pink-blossoms"
description: "Get the Pink Blossoms inventory"
inputs: {}
outputs:
  items_json:
    description: "A json map of items to prices"
runs:
  using: "node12"
  main: "dist/index.js"
