on:
  push:
  schedule:
    - cron: "6 * * * *"

jobs:
  pink_blossoms:
    runs-on: ubuntu-latest
    name: Pink Blossoms
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Pink Blossoms Inventory
        uses: ./ # Uses an action in the root directory
        id: get_inventory
      - name: Save Data
        run: |-
          mkdir -p data
          echo ${{ toJSON(steps.get_inventory.outputs.items) }} | jq --sort-keys '.' > data/pink_blossoms.json
      - name: Commit and push if it changed
        id: commit
        run: |-
          git config user.name "Scraper"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          if git commit -m "Pink Blossoms update"; then
            git push
            echo '::set-output name=updated::true'
          else
            echo '::set-output name=updated::false'
          fi
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        if: ${{ steps.commit.outputs.updated == 'true' }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Pink Blossoms Inventory Update
          body: file://data/pink_blossoms.json
          to: zackhsi@gmail.com
          from: Scraper
