on:
  push:
  schedule:
    - cron: "6 * * * *"

jobs:
  pink_blossoms:
    runs-on: ubuntu-latest
    name: Pink Blossoms
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Pink Blossoms Inventory
        uses: ./ # Uses an action in the root directory
        id: pink_blossoms
      - name: Save Data
        run: |-
          mkdir -p data
          echo ${{ toJSON(steps.pink_blossoms.outputs.items) }} | jq --sort-keys '.' > data/pink_blossoms.json
      - name: Commit and push if it changed
        id: commit
        run: |-
          git config user.name "Scraper"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Pink Blossoms: ${timestamp}" || exit 1
          git push
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        if: ${{ success() }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Pink Blossoms Inventory Update
          body: file://data/pink_blossoms.json
          to: zackhsi@gmail.com
          from: Scraper
